### ISSUE TITLE
Cant run ansible

### ISSUE THREAD

**Issue by PipeVerri** [BaptisteBdn/ansible-dotfiles#1]
I did the exact same steps detailed in the README.md, i installed ansible on arch using:
`sudo pacman -S ansible`
everytime i run the command, i get this error:

ERROR! couldn't resolve module/action 'kewlfft.aur.aur'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/pipe/Escritorio/ansible-dotfiles/ansible/roles/packages/tasks/main.yml': line 34, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

\# Use : ansible-galaxy collection install kewlfft.aur
- name: Install AUR needed packages using yay
  ^ here

**Comment by BaptisteBdn** [comment]
Hello,
Thank you for using the playbook !
Did you follow the requirements on the Readme and installed the ansible collections with the following commands ?
```
ansible-galaxy collection install community.general
ansible-galaxy collection install kewlfft.aur
```

**Comment by PipeVerri** [comment]
Hello, thanks for your answer, now it runs but i ran into another error when it tries to install the packages:

fatal: [localhost]: FAILED! => {"changed": false, "msg": "failed to install alacritty blueman bluez-utils flameshot fzf geeqie otf-font-awesome playerctl polybar python-pywal zsh: error: target not found: polybar\n"}


I will try to skip the packages installation and install them manually, i think the error is because polybar isnt in the pacman repository

**Comment by PipeVerri** [comment]
I managed to install it, before i close this issue, this is how i did it:
1) I deleted the packages role to install them manually
2) I installed every package using pacman including i3-gaps and rofi except for polybar
3) Installed polybar using yay
4) Configured the dot files using the ansible playbook
