### ISSUE TITLE
main.yml could not be found

### ISSUE THREAD

**Issue by Trexxin** [BaptisteBdn/ansible-dotfiles#2]
While following the directions, I encountered this error when trying the `ansible-playbook --inventory hosts --connection=local main.yml` command

The output for this command is 
`ERROR! the playbook: main.yml could not be found`

Using the `ls` command I was able to see that the file did exist as show below.
![image](https://user-images.githubusercontent.com/52933202/143494357-745115dc-da4e-4cac-bfe8-6a829e501da2.png)

Do you have idea what could be causing this? I am using arch btw

**Comment by BaptisteBdn** [comment]
Hello, 
You are calling the `main.yml` but you are not in the good directory.
Two solutions : 
- do `cd ansible-dotfiles/ansible` and execute `ansible-playbook --inventory hosts --connection=local main.yml`
- do `ansible-playbook --inventory hosts --connection=local ansible-dotfiles/ansible/main.yml`

**Comment by Trexxin** [comment]
Yes that appeared to the the problem. After launching the playbook however, I then encountered an error stating it failed to install all packages.

![image](https://user-images.githubusercontent.com/52933202/143506583-fd7bfd72-76a0-40dc-b4e2-d0ce61b7d436.png)

Looking at the only other issue for this repo, I saw someone had a similar problem and just installed the packages manually so I will also do the same. I don't know what caused this error though.
#1
