### ISSUE TITLE
How to tie the installation of these dotfiles to BaptisteBdn/dotfiles repo

### ISSUE THREAD

**Issue by Trexxin** [BaptisteBdn/ansible-dotfiles#3]
Hi, after finishing your instructions I realized that the dotfiles I had downloaded were not the same/linked to your `BaptisteBdn/dotfiles` repo. How would I go about using this to install the dotfiles located in that repo as you said "For an easy way to install and use those dotfiles, please check ansible-dotfiles"?

![image](https://user-images.githubusercontent.com/52933202/143526366-f17c6f17-08db-4d10-83bb-b1b52f5a253a.png)

**Comment by BaptisteBdn** [comment]
Hello,
This is odd, this repo should install the dotfiles available on `BaptisteBdn/dotfiles`. The variable is set to `dotfiles_repo: "https://github.com/BaptisteBdn/dotfiles"`.
Can you tell me more about your problem ? What is missing ?
From what I can see on the screenshot, it looks quite good, have you tried restarting your computer to start a new environnement ?

**Comment by noyrea** [comment]
Just a guess, but I think that we're missing a lot of the basic packages, some of the ones that are used in the setup are not installed by: `ansible-playbook --inventory hosts --connection=local main.yml --ask-become-pass`

**_Keep in mind that while I specify Archlinux, I used EndeavourOS for simplicity which install basics i3 dependencies so you may be missing some packages (like i3 for example)._**
- _This is probably why_


For example, in my setup rofi, and thunar weren't there so I grabbed them and then they started working. I'm not sure if nitrogen was something that was included either but when I got that wallpapers started working albeit at the wrong resolution.

Is there some way to find out which packages we're missing? Or did I do something completely wrong, and it's much simpler?

**Comment by Trexxin** [comment]
I'm at work rn and after I'm off I send a more detailed  answer but it may be nitrogen that I'm missing as I manually installed the i3 dependencies. Also I could find out what packages come with your os and compare them to arch to se the difference. Sorry for the late reply!

**Comment by Trexxin** [comment]
I'm at work rn and after I'm off I send a more detailed  answer but it may be nitrogen that I'm missing as I manually installed the i3 dependencies. Also I could find out what packages come with your os and compare them to arch to se the difference. Sorry for the late reply!

**Comment by Trexxin** [comment]
> Hello, This is odd, this repo should install the dotfiles available on `BaptisteBdn/dotfiles`. The variable is set to `dotfiles_repo: "https://github.com/BaptisteBdn/dotfiles"`. Can you tell me more about your problem ? What is missing ? From what I can see on the screenshot, it looks quite good, have you tried restarting your computer to start a new environnement ?

Following what noyrea said, I installed nitrogen and after a reboot I was able to get the wallpaper working. 
![image](https://user-images.githubusercontent.com/52933202/143668608-4fe08660-76bf-4c61-8f52-33bd8abcbd4c.png)

However, when trying to open the .dotfiles folder I get this error:
![image](https://user-images.githubusercontent.com/52933202/143668657-82d88bff-f49d-41a4-a0a8-213010b98edf.png)

This was weird as I had the repo cloned from earlier so I decided to try and get it again. But doing so reinstated the fact that I had the repo installed as shown:
![image](https://user-images.githubusercontent.com/52933202/143668708-dc9a8453-9d53-44e2-a46e-7f4018b34ab7.png)

Even more so when trying to enter any other folder such as workspace I get the same error as shown:
![image](https://user-images.githubusercontent.com/52933202/143668725-030d1d15-2dbc-4574-8518-24a9f534c8b9.png)

So I though that maybe something got misconfigured so I reran the `ansible-playbook` command which outputted:
![image](https://user-images.githubusercontent.com/52933202/143669508-06377fb0-159a-4ba9-8cbe-6db535b9d3ce.png)

The 'change' was when I changed the file path for the .zshrc file as I had to change the name from yours to mine. So after undonig that change the same message:
![image](https://user-images.githubusercontent.com/52933202/143669657-36d5ce0d-eec2-4092-ab34-5adf1d399d84.png)

Im really tempted to just switch Os's at this point kek. No other file was changed in the local repo.

I am deciding between just reinstalling arch and redoing the process again or just installing your os to make life easier.

**Comment by BaptisteBdn** [comment]
> Just a guess, but I think that we're missing a lot of the basic packages, some of the ones that are used in the setup are not installed by: `ansible-playbook --inventory hosts --connection=local main.yml --ask-become-pass`
> 
> **_Keep in mind that while I specify Archlinux, I used EndeavourOS for simplicity which install basics i3 dependencies so you may be missing some packages (like i3 for example)._**
> 
>     * _This is probably why_

You are right, packages are missing as they are installed by default on EndeavourOS.
You can find the of packages installed with the OS [here](https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-packages-lists/master/i3).
I will try to install a brand new arch OS and updated the packages to include everything.


> However, when trying to open the .dotfiles folder I get this error: ![image](https://user-images.githubusercontent.com/52933202/143668657-82d88bff-f49d-41a4-a0a8-213010b98edf.png)

Are you using Thunar when you are trying to open the files ?
I have included the thunar config file into my dotfiles to not loose my shortcut, however is it using the full path for the shortcuts.
The dotfile is located [here](https://github.com/BaptisteBdn/dotfiles/blob/main/.config/gtk-3.0/bookmarks), you should find yours in ` ~/.dotfiles/.config/gtk-3.0/bookmarks`, check that it exists and change or delete the paths, Thunar should work after that.

**Comment by Trexxin** [comment]
Yep that fixed thunar. Everything seems to working now.
